(* DO NOT EDIT THIS FILE *)

module M = Author

let () = 
  if List.nth M.hours_worked 0 < 0 && List.nth M.hours_worked 1 < 0
     && List.nth M.hours_worked 2 < 0 && List.nth M.hours_worked 3 < 0
  then print_string
      "===========================================================\n\
       WARNING: \n\
       You have not set hours_worked. Please read the submission\n\
       instructions in the assignment handout.\n\
       ===========================================================\n"